defaults:
  - config
  - _self_

log_root_prefix: ./magicdrive-log/test

runner:
  validation_batch_size: 4

resume_on_exists: false
show_box: true

fix_seed_for_every_generation: False

gen_train_set: false