# @package _global_
defaults:
  - /dataset/Nuscenes_map_cache_box
  # - /runner/8gpus
  - model: ../../model/SDv1.5mv_rawbox
  - _self_  # make sure override

task_id: 256x704

dataset:
  image_size: [256, 704] # bevfusion preferred
  back_resize: [533, 1466]  # (h, w)
  back_pad: [67, 367, 67, 0]  # left, top, right and bottom
  augment2d:
    # from bevfusion augment2d.resize L14: https://github.com/mit-han-lab/bevfusion/blob/5b08cc8ceef9c3792253c4d3b7431ca599d3d882/configs/nuscenes/default.yaml
    # from bevfusion test-pipeline L195: https://github.com/mit-han-lab/bevfusion/blob/5b08cc8ceef9c3792253c4d3b7431ca599d3d882/configs/nuscenes/det/default.yaml
    resize: [[0.48, 0.48]]
    rotate: null

runner:
  num_train_epochs: 350
  validation_show_box: true
  enable_xformers_memory_efficient_attention: true  # always need this.
  bbox_add_ratio: 0.1
