# @package _global_
defaults:
  - /exp-hd/432x768

task_id: occ_bg_augloss_fusion_hd_432x768
runner:
  train_batch_size: 1
  # learning_rate: 6e-5
  # lr_warmup_steps: 5000
  # checkpointing_steps: 2000
  # validation_steps: 500
  bbox_add_ratio: 0.0 # !!!
  box_add_num: 0 # !!!
  enable_xformers_memory_efficient_attention: true # debug
  # validation_index: [204, 1828]

official_ckpt: pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400
model_save_path: pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400
controlnet_seg_pretrained: sd-controlnet-seg #/diffusion_pytorch_model.bin
resume_from_checkpoint: magicdrive-log/SDv1.5mv-rawbox_2024-07-30_06-17_occ_bg_augloss_fusion_hd/checkpoint-152000

save_model_only: false



# using mask based auxiliary loss
use_aug_loss: true
# using txt_con_fusion
model:
  controlnet:
    use_txt_con_fusion: true